### ISSUE TITLE
How I leave cockpit view and go back to normal view?

### ISSUE THREAD

**Issue by gabrsar** [FirstPersonKSP/RasterPropMonitor#152]
**Describe the bug**
When I press launch on the VAB, my game goes inside in the cockpit view, and I cannot go back to normal view, no matter what buttons I press.

**To Reproduce**
1. Install Mods
2. Start new game
3. Go to VAB
4. Build Rocket
5. Press Launch
6. You're stuck in Cockpit view

**Expected behavior**
I expect to be able to go back to the default view, and alternate between both.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11
 - Steam
 - KSP: 1.25.5.3190
 - RPM: 1.0.2

**Comment by JonnyOThan** [comment]
There are two mods that do this intentionally: QuickIVA and ThroughTheEyes.  Check the settings if you have those installed. Since you did not include a log file, I can’t tell if you do or not.

Another thing that sometimes happens is that the C key can get unbound in the keyboard settings. Double check that it’s still bound. And then finally, the mode mask on the key can get set to 0.  You need to edit the settings.cfg file to change it to -1 if this happens.
